version: 2

sources:
    - name: raw
      schema: raw
      tables:
          - name: aisles
          - name: departments
          - name: products
          - name: orders
          - name: order_products
