version: 2

sources:
    - name: raw
      description: >
          A publicly available, anonymized collection from Instacart (a U.S. online grocery delivery service).
          Released in 2017 via Kaggle, it includes over 3 million grocery orders from more than 200,000 users,
          spanning 4-100 orders per user.
      database: dbt
      schema: raw
      tables:
          - name: aisles
            columns:
                - name: aisle_id
                  data_type: integer
                  tests:
                      - not_null
                      - unique
                - name: aisle
                  data_type: text
          - name: departments
            columns:
                - name: department_id
                  data_type: integer
                  tests:
                      - not_null
                      - unique
                - name: department
                  data_type: text
                  tests:
                      - unique
                      - not_null

          - name: products

          - name: orders

          - name: order_products
            columns:
                - name: order_id
                  data_type: integer
                  tests:
                      - not_null
                      - relationships:
                            field: order_id
                            to: source('raw', 'orders')
                - name: product_id
                  data_type: integer
                  tests:
                      - not_null
                      - relationships:
                            field: product_id
                            to: source('raw', 'products')
                - name: add_to_cart_order
                  data_type: integer
                - name: reordered
                  data_type: integer

          - name: test
            description: "A test table for learning"
            columns:
                - name: id
                  tests:
                      - unique
                - name: name
                  tests:
                      - not_null
                - name: loaded_at
                  tests:
                      - not_null
            freshness:
                error_after:
                    count: 2
                    period: hour
                warn_after:
                    count: 1
                    period: hour
            loaded_at_field: loaded_at
